### ISSUE TITLE
Plugin not woring? 

### ISSUE THREAD

**Issue by Jcuttin50** [geheur/clue-juggling-timers#1]
Hey man! Been trying to find a way to contact you, any chance you can have a look at the clue juggling timer? I don't understand all this but use your plug in a  lot.

Thanks man.

**Comment by geheur** [comment]
yeah I submitted a fix hopefully they will accept it soon https://github.com/runelite/plugin-hub/pull/2601

**Comment by geheur** [comment]
This has been fixed.
