### ISSUE TITLE
Timer seems bugged

### ISSUE THREAD

**Issue by RichDataAK** [geheur/clue-juggling-timers#10]
Whenever I drop a clue, the infoboxes aren't rendering at all. I'm on a jagex account > which plays runelite. I've uninstalled and re-installed the plugin. No luck. The infoboxes simply aren't rendering at all. 

Also, a clan member of mine mentioned that when they drop their clue(s), there is a time shown for 60 minutes, but when they logout and log back in, the timer drops to 16 minutes. No matter how many times they pick up the clue and drop it again, the clue timer remains at 16 minutes. 
![image](https://github.com/geheur/clue-juggling-timers/assets/65311783/5f6525da-c61e-4886-bf09-ee5196d9a605)

**Comment by RichDataAK** [comment]
Edit: The clan mate let the 16 minute timer expire for the clue that was picked up and dropped. The timer disappeared but the clue remains. 

Tested picking up the same clue and dropping it, and the same 16 minute timer appears. 

Runelite has been completely re-opened and plugin uninstalled/reinstalled. Hope this helps with debugging!

**Comment by geheur** [comment]
does it happen on 1.10.31.2? the newest version?

**Comment by RichDataAK** [comment]
> does it happen on 1.10.31.2? the newest version?

I've relaunched Runelite and mine's working perfectly now. I've pinged my clan member to verify resolution of his bug as well. Will post back as soon as I know. Thank you for the quick turnaround!

**Comment by RichDataAK** [comment]
> does it happen on 1.10.31.2? the newest version?

Verified with my other clan member and it's properly tracking the 60 minutes. 

Thank you again!!
