### ISSUE TITLE
[Bug] - Challenge scroll (elite) infobox shows incorrect item

### ISSUE THREAD

**Issue by newtonkwan** [geheur/clue-juggling-timers#13]
Behavior: 
When dropping the Challenge scroll (elite) on the ground, an unknown item appears in the infobox (see below picture)
https://i.imgur.com/YM7LtZO.png

I verified that, for example, the master clue when dropped on the ground still has the correct behavior. 

Expected: 
Info box shows the Elite clue icon when Challenge scroll (elite) is on the ground.

**Comment by newtonkwan** [comment]
Someone told me that it's Sherlock's hat and this is intended, so I'll close this. Learn something new everyday.

**Comment by geheur** [comment]
that is correct, I wanted to make it look different from a normal elite clue and I thought this would be appropriate since challenge scrolls only come from sherlock iirc.
Does look kind of like the food you make the goblin generals to free them from the time spell though.
