### ISSUE TITLE
[Suggestion] Setting to only show the oldest clue scroll

### ISSUE THREAD

**Issue by Valdevon** [geheur/clue-juggling-timers#4]
Since the 1 hour clue scroll change, a lot of people are now juggling many clues, potentially up to multiple dozen clues at a time. 

This plugin can be very useful for tracking when you have to rejuggle all your clues, but with many clue scrolls on the ground the info box gets really annoying. I suggest to have a toggle in the plugin settings to only show the timer for the oldest clue scroll.

This way you can use the plugin to know both when you have to juggle your clues again, and if you successfully rejuggled all the clues and didnt miss one, without having your infobox extremely cluttered

**Comment by Valdevon** [comment]
To clarify: If you had 5 clues on the ground with timers 50, 40, 30, 20, and 10 minutes, you would have one info box entry showing 10 minutes.

If you juggled the 10 minute clue scroll, the timer would then show 20 minutes as that is the next oldest clue.

**Comment by geheur** [comment]
Added in https://github.com/geheur/clue-juggling-timers/commit/1e40f7b8e582bb5f2e3a1d7e2b90a3576d1eaafe to be released probably in 2.0.
