### ISSUE TITLE
Timer underflows for clues (Timer off by 1 minute)

### ISSUE THREAD

**Issue by Septem151** [geheur/clue-juggling-timers#5]
For some reason, the timer is starting at 58 (59:00) minutes now and extends past the end of the timer by 1 minute.

![image](https://github.com/geheur/clue-juggling-timers/assets/32029081/13be6e24-bfc5-4be6-842e-3dc950d9630a)

This is a regression compared to when the timer changes were first implemented.

**Comment by geheur** [comment]
yes, i have a pr open to fix this.
