### ISSUE TITLE
Negative Timers

### ISSUE THREAD

**Issue by DoctorFeuer** [geheur/clue-juggling-timers#7]
Not entirely sure what I did but I now have multiple timers for hard clues counting down infinitely in the negative, as well as several with red ? on them.

![image](https://github.com/geheur/clue-juggling-timers/assets/165736908/0eb51c74-f208-444d-bbf4-e7493dde46ee)

Any help would be appreciated

**Comment by geheur** [comment]
When does this happen? on login?
Could you send me your `client.log`?
as for fixing it, try running `::clearclues` in in-game chat and then restarting the client.

**Comment by DoctorFeuer** [comment]
It was on login yesterday - today it looks as if it is no longer an issue, likely related to running ::clearclues and restarting. I believe it happened when I dropped multiple clues and tried deleting old ones from the InfoBox. 

I'll update you if the issue happens again, appreciate the response!

**Comment by Frosty-J** [comment]
Hello, this is my first time using the plugin today. After moving my clues from one stack to another to reset the 60-minute timer before leaving the area, I noticed a question mark one in the interface. And now it's counting into the negatives for a clue scroll that doesn't exist (as I've completed all the ones that were in the stack). `client.log` doesn't contain anything useful.

```
2024-04-06 18:33:38 BST [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "clue-scroll-juggling" jar "n8UzkFzVFY-FKG6gjJf4TVnqvksuinkHO8Tk_pfiHBY"
```

**Comment by Frosty-J** [comment]
Wasn't able to reproduce it. I don't know what happened. In my hour of recording, the only remotely noteworthy thing is the timer for beginner clues disappears after one is picked up from the pile.

https://github.com/geheur/clue-juggling-timers/assets/60154347/bb72a2df-8855-4720-a038-27e3747d2ada

**Comment by geheur** [comment]
This might be fixed in 2.0.2. Please let me know if you see it happen again.

**Comment by geheur** [comment]
I assume this is now fixed. Please re-open if it's not.

**Comment by Frosty-J** [comment]
Found a way to reproduce the question mark. Move one stack of clues to the other but do not drop the last one! Like this:

Tile|Tile
-|-
Beginner (3)|(empty)
Beginner (2)|Beginner (1)
Beginner (1)|Beginner (2)

Then close the client and log back in. You'll get a question mark. If you do the same but drop the final one, so `(empty)|Beginner (3)`, it will have the correct remaining time (assuming you didn't log into the game on a different client/device in the meantime).
