### ISSUE TITLE
Timer is wrong and keeps getting more wrong

### ISSUE THREAD

**Issue by MarcusOtter** [geheur/clue-juggling-timers#9]
When I installed this plugin, dropping a hard clue showed me a timer of 230 minutes. The next time I dropped it, it showed 260 minutes. So I fiddled with the drop timer multiplier setting to always set it to 60m, but it keeps drifting as I play. Right now it's up to 415 minutes.

You mentioned in another issue that this plugin essentially uses the ground items plugin, but that one *does* show it correctly. So it seems to me that either this plugin does something wrong or clashes with some other plugin I use (which I assume might be the case as nobody else seems to have reported anything like this)

I really don't have many plugins though, would love some help in getting to the bottom of this.

![image](https://github.com/geheur/clue-juggling-timers/assets/35617441/08b08e79-1777-445d-a062-dce78320bdb8)

**Comment by MarcusOtter** [comment]
Here are the plugins I have installed, most of these are turned off though 

![image](https://github.com/geheur/clue-juggling-timers/assets/35617441/44b05ffe-8b9b-4b21-82d2-fc8fe09623e4)

**Comment by geheur** [comment]
I haven't updated it to use the new drop timer API. presumably that would fix this.
I haven't seen >60m timers, idk how that happens.

**Comment by coopermor** [comment]
![2024-05-11 20_56_08-RuneLite - CooperMor](https://github.com/geheur/clue-juggling-timers/assets/8049699/e6e2ee0b-6220-417a-a77b-0b5fd7b98be5)
The plugin was working for me yesterday but as of today I am also getting timers above 60 minutes.

**Comment by tryTheFace** [comment]
I am also having the same issue, times are off for me 
![image](https://github.com/geheur/clue-juggling-timers/assets/169572317/1c89d789-32b4-4bb5-9fb9-a6f58e92af94)

**Comment by geheur** [comment]
I guess this probably has something to do with some new ground items API that just got added to runelite. I'll take a look.

**Comment by IllogicalSpaz** [comment]
I'm impacted as well :)
![image](https://github.com/geheur/clue-juggling-timers/assets/32830515/a8eab1a3-f0d5-43b0-9992-3d6f44056595)

![image](https://github.com/geheur/clue-juggling-timers/assets/32830515/fa1735e8-dd9b-436a-bb50-9bb2c32d0ee1)

Thanks

**Comment by geheur** [comment]
Fixed, go to the plugin hub and update it.

**Comment by IllogicalSpaz** [comment]
Confirmed Working

**Comment by tryTheFace** [comment]
You're goated Geheur

**Comment by Rykee** [comment]
Thanks for the super fast fix!

**Comment by MarcusOtter** [comment]
Legend. Consider setting up a [GitHub Sponsors](https://github.com/sponsors) page :)
